[package]
name = "kronos-ultra"
version = "1.1.6"
description = "Lumo Trade desktop shell"
authors = ["Kronos"]
edition = "2021"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = ["tray-icon", "image-png"] }
tauri-plugin-positioner = { version = "2", features = ["tray-icon"] }
tauri-plugin-notification = "2"

